### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by palewire** [palewire/django-yamlfield#13]
Here's a warning that comes out these days.

```
RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
 class YAMLField(models.TextField):
```

**Comment by glow-mdsol** [comment]
I have a PR almost ready to resolve this, but I wanted to check - can we drop support for 1.7.10?  
See 
* https://github.com/glow-mdsol/django-yamlfield/tree/feature/replace_subfield_base
* https://travis-ci.org/glow-mdsol/django-yamlfield

**Comment by palewire** [comment]
Yes that's fine.

**Comment by glow-mdsol** [comment]
Ok, https://github.com/datadesk/django-yamlfield/pull/14
